register_tool("Show site response", function()
    local site = input("Enter site: ")
    local http = HttpClient.new()
    print("Please, wait a bit...")
    local resp = http:get(site)
    print(resp.text)
end)
